// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.controllers').controller('LoginCtrl', [
  '$scope', 'Auth', function($scope, Auth) {
    return $scope.signin = function() {
      if ($scope.name.length === 0 || $scope.password.length === 0) {
        return;
      }
      return Auth.signIn($scope.name, $scope.password);
    };
  }
]);
