// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.controllers').controller('RegisterCtrl', [
  '$scope', 'Auth', function($scope, Auth) {
    return $scope.register = function() {
      if ($scope.email.length === 0 || $scope.password.length === 0) {
        return;
      }
      return console.log('TOTO: add register service');
    };
  }
]);
