// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.services').factory('Auth', [
  'StorageExt', '$window', '$rootScope', '$state', '$log', function(StorageExt, $window, $rootScope, $state, $log) {
    var service;
    service = {
      currentCSR: null,
      login: function(name, password, token) {
        var params;
        params = {
          name: name
        };
        if (password != null) {
          return params.password = md5(password);
        } else {
          return params.token = token;
        }
      },
      signOut: function() {},
      isSignedIn: function() {
        return !!service.currentCSR;
      },
      getToken: function() {
        var _ref, _ref1;
        return (_ref = (_ref1 = service.currentCSR) != null ? _ref1.token : void 0) != null ? _ref : '';
      },
      authed: function(data) {
        var _ref;
        $log.debug(data, ' ->authed');
        data.avatar = (_ref = data.avatar) != null ? _ref : 'images/avatar.png';
        StorageExt.csr.set(data);
        service.currentCSR = data;
        return $state.transitionTo('main');
      }
    };
    return service;
  }
]);
