// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.services').factory('Auth', [
  'StorageExt', '$window', '$rootScope', '$state', '$log', '$q', function(StorageExt, $window, $rootScope, $state, $log, $q) {
    var service;
    service = {
      currentUser: null,
      login: function(name, password, token) {
        var deferred;
        deferred = $q.defer();
        deferred.resolve([
          {
            username: "daemon",
            desc: "。。。。。。",
            avatar: "http://mmbiz.qpic.cn/mmbiz/LibiaVTSibfW4HFHpEJnk8E8J11V4tRs9IedpMAQ3ibj9JuqtH3L8NncZyzXrT4f3icrlyFu8OfGrTqKON6O27TCvqw/0",
            url: "http://mp.weixin.qq.com/s?__biz=MjM5NDA0NTM2MQ==&mid=200013272&idx=1&sn=a8d933d846bc11fbfd09327a708f32d5"
          }
        ]);
        return deferred.promise;
      },
      signOut: function() {},
      isSignedIn: function() {
        return !!service.currentUser;
      },
      getToken: function() {
        var _ref, _ref1;
        return (_ref = (_ref1 = service.currentUser) != null ? _ref1.token : void 0) != null ? _ref : '';
      },
      authed: function(data) {
        var _ref;
        $log.debug(data, ' ->authed');
        data.avatar = (_ref = data.avatar) != null ? _ref : 'images/avatar.png';
        StorageExt.csr.set(data);
        service.currentUser = data;
        return $state.transitionTo('main');
      }
    };
    return service;
  }
]);
