// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.services').factory('Storage', [
  '$window', '$rootScope', function($window, $rootScope) {
    var storage;
    storage = $window.localStorage;
    return {
      set: function(key, value) {
        var saver;
        saver = $window.JSON.stringify(value);
        return storage.setItem(key, saver);
      },
      get: function(key) {
        var item;
        item = storage.getItem(key);
        return $window.JSON.parse(item);
      },
      remove: function(key) {
        return storage.removeItem(key);
      }
    };
  }
]);
