// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.services').factory('StorageExt', [
  'Storage', 'Config', function(Storage, Config) {
    return {
      datetime: {
        getById: function(id) {
          var locals, _ref;
          locals = (_ref = Storage.get(Config.storageKey.lastdate)) != null ? _ref : {};
          return locals[id];
        },
        setById: function(id, datetime) {
          var locals, _ref;
          locals = (_ref = Storage.get(Config.storageKey.lastdate)) != null ? _ref : {};
          locals[id] = datetime;
          return Storage.set(Config.storageKey.lastdate, locals);
        }
      },
      csr: {
        get: function() {
          return Storage.get(Config.storageKey.csr);
        },
        set: function(data) {
          return Storage.set(Config.storageKey.csr, data);
        }
      },
      unread: {
        getById: function(id) {
          var locals, _ref;
          locals = (_ref = Storage.get(Config.storageKey.unread)) != null ? _ref : {};
          return locals[id];
        },
        set: function(data) {
          return Storage.set(Config.storageKey.unread, data);
        },
        add: function(id, data) {
          var locals, _ref;
          locals = (_ref = Storage.get(Config.storageKey.unread)) != null ? _ref : {};
          if (locals[id] == null) {
            locals[id] = [];
          }
          locals[id].push(data);
          return Storage.set(Config.storageKey.unread, locals);
        },
        remove: function(id) {
          var locals;
          locals = Storage.get(Config.storageKey.unread);
          locals[id] = [];
          return Storage.set(Config.storageKey.unread, locals);
        }
      }
    };
  }
]);
