// Generated by CoffeeScript 1.7.1
'use strict';
if (String.prototype.trim == null) {
  String.prototype.trim = function() {
    return this.replace(/(^\s*)|(\s*$)/g, '');
  };
}

angular.module('weichejianFrontApp', ['ngCookies', 'ngSanitize', 'ngAnimate', 'ngResource', 'ui.router', 'pascalprecht.translate', 'common.config', 'weichejian.locales', 'weichejian.services', 'weichejian.controllers', 'weichejian.states']);

angular.module('weichejian.locales', []);

angular.module('weichejian.services', []);

angular.module('weichejian.controllers', []);

angular.module('weichejian.states', []);

angular.module('weichejianFrontApp').constant('App', {
  name: '微车间',
  version: '0.0.1'
}).run([
  '$rootScope', 'App', function($rootScope, App) {
    $rootScope.app = App;
    return document.title = App.name;
  }
]).run([
  '$rootScope', '$state', 'Auth', function($rootScope, $state, Auth) {
    var statesNotRequireAuth;
    statesNotRequireAuth = ['/', 'login'];
    return $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
      if (!Auth.isSignedIn() && !(_.contains(statesNotRequireAuth, toState.name))) {
        event.preventDefault();
        return $state.transitionTo('/');
      }
    });
  }
]);
