// Generated by CoffeeScript 1.7.1
'use strict';
angular.module('weichejian.states').config([
  '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    return $stateProvider.state('/', {
      url: '/',
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).state('signin', {
      url: '/signin',
      templateUrl: 'views/signin.html',
      controller: 'SignInCtrl'
    }).state('main', {
      url: '/main',
      templateUrl: 'views/main.html',
      controller: 'MainCtrl',
      resolve: {
        customers: [
          'Customer', function(Customer) {
            return Customer.fetch();
          }
        ],
        unreads: [
          'Unread', function(Unread) {
            return Unread.fetch();
          }
        ]
      }
    });
  }
]);
